name: Pipeline
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "postgresql+psycopg://app_user:app_password@localhost:5432/app_db"
      SECRET_KEY: "your-secret-key"
      ALGORITHM:  "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    steps:
      - name: Copy repo files
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Check Python version
        run: python --version

      - name: Install Poetry
        run: |
          python -m pip install pipx
          pipx install poetry

      - name: Force Poetry to use Python 3.12
        run: poetry env use python3.12

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install

      - name: Tests
        run: poetry run task test
